[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
sqlx.workspace = true
bigdecimal.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
chrono.workspace = true
